### ISSUE TITLE
Привіт!

### ISSUE THREAD

**Issue by Wandalen** [Arideno/rust-book-uk#1]
Привіт!
Дякую за перклад. 
Скажи, будь ласка, на скільки він повний/якісний?

**Comment by KlimMixer** [comment]
Привіт, поки що лише перший розділ.

**Comment by Wandalen** [comment]
Це дуже крута ініціатива. Ми як вітка Rust спільноти саме запускаємо робочу групу по перекладу. Вже маємо 10 волонтерів. Можливо ти маєш бажання очолити цю групу або взяти в ній участь? 

Напиши, будь ласка, мені в телеграм @wandalen_me чи дай свій. Давай це обговоримо.
